-- AlterTable
ALTER TABLE "lojas" ADD COLUMN     "instagram" TEXT NOT NULL DEFAULT 'SEM_INSTAGRAM',
ADD COLUMN     "local" TEXT NOT NULL DEFAULT 'SEM_LOCAL',
ADD COLUMN     "whatsapp" TEXT NOT NULL DEFAULT 'SEM_WHATSAPP';
