-- AlterTable
ALTER TABLE "hospedagens" ADD COLUMN     "instagram" TEXT NOT NULL DEFAULT 'SEM_INSTAGRAM',
ADD COLUMN     "whatsapp" TEXT NOT NULL DEFAULT 'SEM_WHATSAPP';

-- AlterTable
ALTER TABLE "malharias" ADD COLUMN     "instagram" TEXT NOT NULL DEFAULT 'SEM_INSTAGRAM',
ADD COLUMN     "whatsapp" TEXT NOT NULL DEFAULT 'SEM_WHATSAPP';

-- AlterTable
ALTER TABLE "quiosques" ADD COLUMN     "instagram" TEXT NOT NULL DEFAULT 'SEM_INSTAGRAM',
ADD COLUMN     "whatsapp" TEXT NOT NULL DEFAULT 'SEM_WHATSAPP';

-- AlterTable
ALTER TABLE "restaurantes" ADD COLUMN     "instagram" TEXT NOT NULL DEFAULT 'SEM_INSTAGRAM',
ADD COLUMN     "whatsapp" TEXT NOT NULL DEFAULT 'SEM_WHATSAPP';

-- AlterTable
ALTER TABLE "transportadoras" ADD COLUMN     "instagram" TEXT NOT NULL DEFAULT 'SEM_INSTAGRAM',
ADD COLUMN     "whatsapp" TEXT NOT NULL DEFAULT 'SEM_WHATSAPP';
